version: '3.3'

services:
  nginx:
    container_name: client
    image: nginx:latest
    volumes:
      - ${PWD}/api.files/:/var/www/api
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/logs/nginx/:/var/log/nginx/
    environment:
      TZ: 'Europe/Madrid'
    ports:
      - '8080:80'